[package]
name = "penumbra-proto-compiler"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
prost = "0.11"
prost-types = "0.11"
prost-build = "0.11"
tonic-build = "0.8.0"
pbjson = "0.5"
pbjson-types = "0.5"
pbjson-build = "0.5"
tempfile = "3"

ibc-proto = "0.26"
ics23 = "0.10.0"
