[package]
name = "penumbra-view"
version = "0.51.0"
authors = ["Penumbra Labs <team@penumbra.zone>"]
edition = "2021"
description = "The view RPC library for the Penumbra Zone"
repository = "https://github.com/penumbra-zone/penumbra/"
homepage = "https://penumbra.zone"
license = "MIT OR Apache-2.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
# When this feature is enabled, the view worker will request every single
# SCT root, to pinpoint exactly where any SCT root divergence occurs.
sct-divergence-check = []

[dependencies]
# Workspace dependencies
penumbra-proto = { path = "../proto", features = ["rpc"] }
penumbra-chain = { path = "../chain" }
penumbra-crypto = { path = "../crypto" }
penumbra-tct = { path = "../tct" }
penumbra-transaction = { path = "../transaction" }
penumbra-shielded-pool = { path = "../crates/shielded-pool", default-features = false, features = ["proving-keys"] }
penumbra-ibc = { path = "../crates/ibc", default-features = false }
penumbra-dao = { path = "../crates/dao", default-features = false }
penumbra-sct = { path = "../crates/sct", default-features = false }
penumbra-compact-block = { path = "../crates/compact-block", default-features = false }
# TODO: replace by a penumbra-app
penumbra-app = { path = "../app" }

ibc-types = { git = "https://github.com/penumbra-zone/ibc-types", branch = "0.2.x" }

tokio = { version = "1.22", features = ["full"] }
tokio-stream = { version = "0.1.8", features = ["sync"] }
anyhow = "1"
rand_core = { version = "0.6.3", features = ["getrandom"] }
rand = "0.8"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = "0.2"
tonic = "0.8.1"
url = "2"
bytes = { version = "1", features = ["serde"] }
prost = "0.11"
futures = "0.3"
hex = "0.4"
metrics = "0.19.0"
async-stream = "0.2"
parking_lot = "0.12"
clap = { version = "3", features = ["derive"] }
camino = "1"
async-trait = "0.1"
tendermint = "0.31.0"
sha2 = "0.10.1"
ed25519-consensus = "2.1"
r2d2 = "0.8"
# Depending on our fork of r2d2-sqlite, which updates the rusqlite dependency to 0.29
r2d2_sqlite = { version = "0.22", git = "https://github.com/penumbra-zone/r2d2-sqlite.git", features = [
    "bundled",
] }
genawaiter = "0.99"
digest = "0.9"
once_cell = "1"

[build-dependencies]
vergen = "5"
